---
# Global variables for Laravel development environment
# This file contains non-sensitive configuration variables

# PHP Configuration
php_versions_available: ["8.1", "8.2", "8.3", "8.4"]
default_php_version: "8.3"  # More stable than 8.4
php_version_list: ["8.3"]  # PHP versions to install
php_extensions:
  - fpm
  - cli
  - common
  - mysql
  - pgsql
  - mbstring
  - xml
  - curl
  - zip
  - gd
  - intl
  - bcmath
  - soap
  - xdebug
  - redis
  - phar

# Node.js Configuration
node_version: "18"  # LTS version
npm_global_packages:
  - npm
  - yarn

# Database Configuration
supported_db_systems: ["mysql", "postgres", "sqlite"]
db_systems: "mysql"  # Default database systems to install
install_mysql: true
install_postgres: false
install_sqlite: false

# Nginx Configuration
nginx_worker_processes: auto
nginx_worker_connections: 1024

# Security Configuration
security_updates_enabled: true
fail2ban_enabled: false  # Disabled for development environment

# Development Environment Settings
development_mode: true
debug_enabled: true
verbose_logging: false

# Service Configuration
services_to_enable:
  - nginx
  - cron

# Default Site Configuration
default_site_config:
  port: 80
  ssl_enabled: false
  auto_update: false
  php_version: "{{ default_php_version }}"

# Sample site configuration
create_sample: true
sample_site_name: "laravel"

# Adminer configuration
adminer_enabled: true