---
# Laravel site role handlers

- name: nginx config test and reload
  command: nginx -t
  become: yes
  notify: reload nginx if config valid
  changed_when: false

- name: reload nginx if config valid
  service:
    name: nginx
    state: reloaded
  become: yes