version: '3.8'

services:
  app:
    image: serversideup/php:8.3-fpm-nginx # Or my-laravel-prod
    container_name: laravel-app-prod
    ports:
      - "80:8080"
    volumes:
      - ../:/var/www/html:ro
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthcheck" ]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql-prod
    profiles:
      - mysql

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: laravel-postgres-prod
    profiles:
      - postgres
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: laravel-redis-prod
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
