version: '3.8'

services:
  app:
    image: serversideup/php:8.3-fpm-nginx
    container_name: laravel-app-dev
    ports:
      - "8080:8080"
    volumes:
      - ../:/var/www/html
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthcheck" ]
      interval: 30s
      timeout: 3s
      retries: 3

  db:
    image: mysql:8.0
    container_name: laravel-mysql-dev
    profiles:
      - mysql
    env_file:
      - ../.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootsecret}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  db_postgres:
    image: postgres:16
    container_name: laravel-postgres-dev
    profiles:
      - postgres
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: laravel-redis-dev
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  postgres_data:
