services:
  app:
    build: .
    context: ..
    dockerfile: docker/common/dockerfile
    container_name: laravel-app-prod
    ports:
      - "80:8080"
    volumes:
      - ../:/var/www/html:ro
    env_file:
      - ../.env
    profiles:
      - default
      - mysql
      - postgres
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthcheck" ]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql-prod
    profiles:
      - default
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - ../.env

    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: laravel-postgres-prod
    profiles:
      - postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    profiles:
      - redis
    container_name: laravel-redis-prod
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
