services:
  app:
    build:
      context: ..
      dockerfile: docker/common/dockerfile.dev
    container_name: laravel-app-dev
    ports:
      - "8000:8080"  # Different port for dev
      - "5173:5173"  # Vite dev server
    volumes:
      - ../:/var/www/html  # Writable mount for development
    env_file:
      - ../.env
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # Remove depends_on - let the app handle database connections with retries
    profiles:
      - default
      - mysql
      - postgres
      - redis

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql-dev
    ports:
      - "3306:3306"  # Expose for external tools
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_dev_data:/var/lib/mysql
    profiles:
      - default
      - mysql
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: laravel-postgres-dev
    ports:
      - "5432:5432"  # Expose for external tools
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    profiles:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: laravel-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    profiles:
      - redis
    restart: unless-stopped

volumes:
  mysql_dev_data:
  postgres_dev_data:
  redis_dev_data: