---
# Ansible inventory file for local execution

all:
  hosts:
    localhost:
      ansible_connection: local
      
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Common variables can be defined here 