---
# Input validation tasks for Laravel environment setup
# Include this file in playbooks to validate user inputs

- name: Validate PHP versions
  fail:
    msg: "Invalid PHP version: {{ item }}. Must be in format X.Y (e.g., 8.1, 8.2, 8.3, 8.4)"
  when: not (item | validate_php_version)
  loop: "{{ php_version_list | default([]) }}"
  tags: ['validation', 'php']

- name: Validate default PHP version
  fail:
    msg: "Invalid default PHP version: {{ default_php_version }}. Must be in format X.Y"
  when: default_php_version is defined and not (default_php_version | validate_php_version)
  tags: ['validation', 'php']

- name: Validate database systems selection
  fail:
    msg: "Invalid database system: {{ item }}. Must be one of: mysql, postgres, sqlite"
  when: item not in ['mysql', 'postgres', 'sqlite']
  loop: "{{ db_systems.split() | default([]) }}"
  tags: ['validation', 'database']

- name: Ensure at least one database system is selected
  fail:
    msg: "At least one database system must be selected"
  when: db_systems is defined and (db_systems | length == 0 or db_systems.split() | length == 0)
  tags: ['validation', 'database']

- name: Validate site names for multi-site setup
  fail:
    msg: "Invalid site name: {{ item.name }}. Site names must contain only alphanumeric characters and underscores"
  when: 
    - laravel_sites is defined 
    - laravel_sites | length > 0
    - not (item.name | validate_database_name)
  loop: "{{ laravel_sites | default([]) }}"
  tags: ['validation', 'sites']

- name: Validate site domains
  fail:
    msg: "Invalid domain name: {{ item.domain | default(item.name + '.local') }}. Must be a valid domain format"
  when: 
    - laravel_sites is defined 
    - laravel_sites | length > 0
    - not ((item.domain | default(item.name + '.local')) | validate_domain_name)
  loop: "{{ laravel_sites | default([]) }}"
  tags: ['validation', 'sites']

- name: Validate site ports
  fail:
    msg: "Invalid port: {{ item.port | default('80') }}. Must be between 1-65535 and not a reserved system port"
  when: 
    - laravel_sites is defined 
    - laravel_sites | length > 0
    - not ((item.port | default('80')) | validate_port)
  loop: "{{ laravel_sites | default([]) }}"
  tags: ['validation', 'sites']

- name: Validate Git repository URLs
  fail:
    msg: "Invalid Git repository URL: {{ item.git_repo }}. Must be a valid HTTP(S) or SSH Git URL"
  when: 
    - laravel_sites is defined 
    - laravel_sites | length > 0
    - item.git_repo is defined
    - item.git_repo != ""
    - not (item.git_repo | validate_git_url)
  loop: "{{ laravel_sites | default([]) }}"
  tags: ['validation', 'sites', 'git']

- name: Validate Node.js version
  fail:
    msg: "Invalid Node.js version: {{ node_version }}. Must be a number (e.g., 16, 18, 20)"
  when: 
    - node_version is defined
    - not (node_version | string | regex_match('^[0-9]+$'))
  tags: ['validation', 'nodejs']

- name: Sanitize user inputs
  set_fact:
    db_systems: "{{ db_systems | sanitize_input }}"
    mysql_root_password: "{{ mysql_root_password | sanitize_input }}"
    postgres_password: "{{ postgres_password | sanitize_input }}"
    adminer_password: "{{ adminer_password | sanitize_input }}"
    sample_site_name: "{{ sample_site_name | sanitize_input }}"
  when: db_systems is defined
  tags: ['validation', 'sanitization']
  no_log: true

- name: Display validation summary
  debug:
    msg: |
      ✅ Input validation completed successfully:
      - PHP versions: {{ php_version_list | join(', ') }}
      - Default PHP: {{ default_php_version }}
      - Database systems: {{ db_systems }}
      - Node.js version: {{ node_version | default('18') }}
      {% if laravel_sites is defined and laravel_sites | length > 0 %}
      - Sites to configure: {{ laravel_sites | length }}
      {% endif %}
  when: verbose_mode | default(false) | bool
  tags: ['validation', 'info']