---
# Nginx role default variables

# Nginx packages and version
nginx_packages:
  - nginx
  - nginx-extras  # For additional modules

# Nginx service configuration
nginx_service_name: nginx
nginx_user: www-data
nginx_group: www-data

# Nginx directories
nginx_conf_dir: /etc/nginx
nginx_sites_available_dir: "{{ nginx_conf_dir }}/sites-available"
nginx_sites_enabled_dir: "{{ nginx_conf_dir }}/sites-enabled"
nginx_log_dir: /var/log/nginx
nginx_cache_dir: /var/cache/nginx
nginx_run_dir: /var/run

# Global nginx.conf settings
nginx_worker_processes: auto
nginx_worker_connections: 1024
nginx_multi_accept: true
nginx_worker_rlimit_nofile: 65535
nginx_keepalive_timeout: 65
nginx_keepalive_requests: 100
nginx_client_max_body_size: 64m
nginx_server_tokens: false  # Hide nginx version

# Performance settings
nginx_sendfile: true
nginx_tcp_nopush: true
nginx_tcp_nodelay: true
nginx_gzip: true
nginx_gzip_vary: true
nginx_gzip_types:
  - text/plain
  - text/css
  - application/json
  - application/javascript
  - text/xml
  - application/xml
  - application/xml+rss
  - text/javascript
  - application/x-font-ttf
  - font/opentype
  - image/svg+xml

# Security settings
nginx_server_names_hash_bucket_size: 64
nginx_types_hash_max_size: 2048
nginx_client_body_timeout: 10
nginx_client_header_timeout: 10
nginx_send_timeout: 10

# SSL/TLS settings (for future use)
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
nginx_ssl_session_cache: "shared:SSL:10m"
nginx_ssl_session_timeout: "10m"

# Default site configuration
nginx_remove_default_site: true
nginx_default_site_enabled: false

# Logging configuration
nginx_access_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for" '
  'rt=$request_time uct="$upstream_connect_time" '
  'uht="$upstream_header_time" urt="$upstream_response_time"'

nginx_error_log_level: warn

# Site management
nginx_sites: []
# Example site configuration:
# nginx_sites:
#   - name: example
#     domain: example.local
#     port: 80
#     root: /var/www/example/public
#     php_version: "8.3"
#     ssl_enabled: false
#     custom_config: ""

# Status and monitoring
nginx_status_enabled: true
nginx_status_path: /nginx_status
nginx_status_allowed_ips:
  - 127.0.0.1
  - ::1

# Rate limiting (for security)
nginx_rate_limit_enabled: true
nginx_rate_limit_zone: "api"
nginx_rate_limit_requests: "10r/s"

# Site information tracking
nginx_site_info_dir: /var/lib/nginx/sites
nginx_generate_site_summary: true