---
# Nginx role handlers

- name: validate nginx config
  command: nginx -t
  become: yes
  register: nginx_validation
  failed_when: nginx_validation.rc != 0

- name: restart nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted
  become: yes

- name: reload nginx
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
  become: yes