---
# PHP configuration task for a specific version and SAPI

- name: Create PHP configuration directory
  file:
    path: "/etc/php/{{ php_version }}/{{ php_sapi }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Check if php.ini exists
  stat:
    path: "/etc/php/{{ php_version }}/{{ php_sapi }}/php.ini"
  register: php_ini_exists

- name: Copy php.ini template if it doesn't exist
  copy:
    src: "/usr/lib/php/{{ php_version }}/php.ini-production"
    dest: "/etc/php/{{ php_version }}/{{ php_sapi }}/php.ini"
    remote_src: yes
    owner: root
    group: root
    mode: '0644'
  when: not php_ini_exists.stat.exists
  become: yes

- name: Configure PHP settings
  lineinfile:
    path: "/etc/php/{{ php_version }}/{{ php_sapi }}/php.ini"
    regexp: "^{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.value }}"
    backup: yes
  loop: "{{ php_settings | dict2items }}"
  become: yes
  notify:
    - restart php-fpm services

- name: Configure PHP development settings
  lineinfile:
    path: "/etc/php/{{ php_version }}/{{ php_sapi }}/php.ini"
    regexp: "^{{ item.key }}\\s*="
    line: "{{ item.key }} = {{ item.value }}"
    backup: yes
  loop: "{{ php_development_settings | dict2items }}"
  when: development_mode | default(true) | bool
  become: yes
  notify:
    - restart php-fpm services

- name: Enable core PHP extensions
  lineinfile:
    path: "/etc/php/{{ php_version }}/{{ php_sapi }}/php.ini"
    regexp: "^;?extension={{ item }}"
    line: "extension={{ item }}"
    backup: yes
  loop:
    - phar
    - mbstring
    - iconv
  become: yes
  notify:
    - restart php-fpm services