---
# Default variables for PHP role

# PHP versions to install
php_versions: ["8.3"]
default_php_version: "8.3"

# PHP extensions to install for each version
php_extensions:
  - fpm
  - cli
  - common
  - mysql
  - pgsql
  - mbstring
  - xml
  - curl
  - zip
  - gd
  - intl
  - bcmath
  - soap
  - xdebug
  - redis

# PHP-FPM configuration
php_fpm_pools:
  - name: www
    user: www-data
    group: www-data
    listen: "/run/php/php{{ default_php_version }}-fpm.sock"
    pm: dynamic
    pm_max_children: 50
    pm_start_servers: 5
    pm_min_spare_servers: 5
    pm_max_spare_servers: 35

# PHP configuration settings
php_settings:
  memory_limit: "256M"
  max_execution_time: "300"
  max_input_vars: "3000"
  upload_max_filesize: "64M"
  post_max_size: "64M"
  date_timezone: "UTC"

# Development settings
php_development_settings:
  display_errors: "On"
  display_startup_errors: "On"
  error_reporting: "E_ALL"
  log_errors: "On"
  xdebug.mode: "develop,debug"

# Production settings (not used in dev environment)
php_production_settings:
  display_errors: "Off"
  display_startup_errors: "Off"
  error_reporting: "E_ERROR | E_WARNING | E_PARSE"
  log_errors: "On"
  xdebug.mode: "off"